# Generated by Django 5.0 on 2023-12-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectPavelPS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='avatars/')),
            ],
        ),
        migrations.DeleteModel(
            name='ModelRegForm',
        ),
        migrations.RenameField(
            model_name='modelpavel',
            old_name='city',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='modelpavel',
            old_name='prof',
            new_name='surname',
        ),
    ]
